name: notify_me_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5 
  connectivity: ^3.0.6
  flutter: 
    sdk: flutter
  cloud_firestore: ^3.1.6
  # flutter_native_splash: ^1.3.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.3.3 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"

  flutter_lints: ^1.0.0
  
   
flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#F0EC18"
  #background_image: "assets/background.png"
  image: assets/images/splash_logo.png
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #ios_content_mode: center
  #android_gravity: center
  #fullscreen: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

flutter: 
  uses-material-design: true

